### ISSUE TITLE
Higher Font Resolution

### ISSUE THREAD

**Issue by LucasHimself** [be-fonts/boring-expansion-spec#3]
_Expansion thoughts designers perspective 2_

The limit of point coordinates in TT-space is currently 2^14. (16384)
I regularly run into this limit. I have made quite a few fonts on 4096 UPM already, when extra detail is important. But then a glyph can not be wider than 4 times the type size, and in fonts with logos or icons, that is not much. A hairline font with rounded corners on 2048 UPM, inside a variable font, will jump awfully while dragging the slider to a darker weight. I was just working on such a font for an industrial customer that cares about quality, but the result is plain ugly. I need to go to 4096 to get acceptable (still not ideal) rounded strokes, but then some icons in the font won't fit in the 2^14 boundary. Using a UPM of 8192 can only work in narrow fonts. 

The limit of 2^14 integers is definitely too small for high quality work. Either we need a bigger drawing board, or coordinates in fractional values.

_(if this has already been taken care of in your proposals, hurray!)_

**Comment by behdad** [comment]
Thanks Luc.

My current thought is that this is hard to change in the short term (the "Boring Expansion"). But in farther stages I'm going to suggest using 32bit floats, which will give us much more resolution (23 bits instead of ~15).

**Comment by davelab6** [comment]
Will that be in https://github.com/be-fonts/better-ergonomics-spec ?

@LucasHimself did you see https://youtu.be/fG1QEcl3yks and https://docs.google.com/presentation/d/1dVfuU7YhUBXg9MtU6kYBXVs9082PiHpwhGPYa--yA7c/ ? :)

**Comment by LucasHimself** [comment]
@davelab6 yes I saw those things, and I found no mentioning of removing the drawing board limitation in TT, so what are you hinting at?

**Comment by behdad** [comment]
> @davelab6 yes I saw those things, and I found no mentioning of removing the drawing board limitation in TT, so what are you hinting at?

The Boring Expansion project will keep the glyf table limitations that you pointed out in tact *so far*. That is, it was not in my scope so far to redesign basic glyf table outline encoding other than to add cubic beziers. But I'll note this request.  Indeed, it's easy enough to add 24bit/32bit integers while changing the format there.

In Better-Ergonomics / Beyond-Emulation worlds wider integers will follow naturally.

Thinking more about it, I agree this limitation is really tight given that we encourage people to use higher UPEM when they ask for more precision.

**Comment by behdad** [comment]
Thinking more, this is out of scope, since I really want to ship Boring Expansion within the rest of the year, and I don't see this happening.
