### ISSUE TITLE
Combined 32bit FormatOffset with more offset bits

### ISSUE THREAD

**Issue by behdad** [be-fonts/boring-expansion-spec#4]
This is one of the tricks I thought of as ugly and hence wasn't planning of pursuing. But seeing #1 and other suggestions re varint encoding, I'm going to put it here for consideration.

Currently, all OpenType Lookup subtables (except for `(Chain)?Context(Subst|Pos)Format3`) start with:
```
  uint16 Format;
  Offset16 Coverage;
```
The Format is currently only used to encode 1, 2, or 3. We can reuse the top byte of format for additional offset bits. That is:
```
  uint8 OffsetTopByte
  uint8 Format;
  uint16 OffsetLow2Bytes
```

This has the nice property that if the offset fits in 16bits, then Format will be parsable by old implementations. If offset is large, then Format will look wrong by old implementations and ignored.

**Comment by rsheeter** [comment]
Gross but I kind of like it.
