### ISSUE TITLE
[`sbix`] >64k expansion

### ISSUE THREAD

**Issue by behdad** [be-fonts/boring-expansion-spec#44]
Consume bit 2 of flags:

Bit 2: Use `numGlyphs` from `loca` table.

If bit 2 is on: for `numGlyphs`, use value derived from `loca` table instead of one from `maxp` table.

See https://github.com/be-fonts/boring-expansion-spec/issues/8 and https://github.com/be-fonts/boring-expansion-spec/issues/6.

**Comment by behdad** [comment]
cc @nedley

**Comment by nedley** [comment]
What is the benefit to doing this rather than changing the `sbix` spec to say something like “use the number of glyphs in the font” rather than saying how the number is calculated as it is now?

**Comment by behdad** [comment]
You are right. I'll do that. Thanks!

**Comment by behdad** [comment]
Superseded by #51.
