### ISSUE TITLE
[colr] Gradient along path

### ISSUE THREAD

**Issue by davelab6** [be-fonts/boring-expansion-spec#53]
Gradient along path would be nice in colrv2; so you can for example have a gradient going along the spine of the `s` or `&`

AFAIK this isn't currently possible without intense effort to use radial and linear gradients to approximate the effect.

**Comment by behdad** [comment]
That would be mesh gradients. Please track in colr repo:

  https://github.com/googlefonts/colr-gradients-spec/issues/312

This spec is for addressing existing pain points in the font format that are not being addressed anywhere else. Thanks.
